### ISSUE TITLE
4.2.0/4.2.1 Breaks InAppBrowser Window on Android Crosswalk

### ISSUE THREAD

**Issue by andybbtt11** [AppGyver/steroids#1082]
I am currently investigating this but I have noticed that the inAppBrowser plugin will cause Android to crash as soon as it is requested. 

I will update this comment with my findings soon, but getting consistent results so far. 

4.1.0/4.2.0/4.2.1 all breaking.  Tried on Galaxy S6 (5.1.1) and Galaxy S4 (4.4). Same results, app crashes as soon as a window.open() with target of "_blank" is called.

**Comment by blanedaze** [comment]
Are you requesting InAppBrowser using window.open()? I just tried it to open an image and it worked, by passing in '_system' instead of '_blank' in the parameter.

**Comment by andybbtt11** [comment]
I will try that in the morning, thanks.

**Comment by andybbtt11** [comment]
This is still an issue, instant crashing on window.open().

**Comment by harsaharsa** [comment]
This is now fixed in Android 4.2.2-edge1, available from the Build Service. Sorry for the long wait!

**Comment by stephan-klein** [comment]
thanks for the fix. However window.open() with '_blank' still crashes when using PlatformWebView instead of Crosswalk. Crosswalk brings so much overhead and i run into different problems. I think PlatformWebView should also be supported. I will open a new issue

**Comment by andybbtt11** [comment]
+1 to @stephan-klein comment.  Our app is still using 4.0.6 platform webview because crosswalk causes too many crashes and slow downs.
