### ISSUE TITLE
Scanner and Apps broken on iOS 10 beta 1 - 3

### ISSUE THREAD

**Issue by boxdrop** [AppGyver/steroids#1118]
Hi there,

just installed the iOS 10 beta 1 on one of our iPhone 6S to check the new possibilities. The AppGyver native Scanner app and all our steroids apps are crashing instantly on open. You may check the attached [scanner-crash.txt](https://github.com/AppGyver/steroids/files/313404/scanner-crash.txt) log for the Scanner app

**Comment by andybbtt11** [comment]
This might be the final nail in the coffin, hope this gets fixed by release or we're doomed :(

**Comment by seanconormcdonnell** [comment]
I just tested this out, can confirm app immediately crashes.

**Comment by boxdrop** [comment]
@harsaharsa any information / schedule for this?

**Comment by christofferh** [comment]
Currently no estimate available. Hopefully we can give an update on this next week.

**Comment by harsaharsa** [comment]
This will definitely get done before the release, and we're striving to have something out before the public beta hits. Sorry for the delay in reacting to this!

**Comment by andybbtt11** [comment]
Thanks a lot @harsaharsa Really good to know.

**Comment by boxdrop** [comment]
@harsaharsa @christofferh any update? public beta is out.

**Comment by roberto-robles** [comment]
Any ETA for this fix, we're really concerned that this affect some of our Users.

**Comment by EdwinRikkers** [comment]
+1

**Comment by rafaeluzzi** [comment]
This has me worried.. can we trust it is going to be fixed before 10 release?  Decisions have to be made otherwise..

**Comment by boxdrop** [comment]
@harsaharsa @christofferh so no news are also news. Very sad about the information politics.

**Comment by jerrybioh** [comment]
could the devs please give us an update?

**Comment by andybbtt11** [comment]
Our iOS crash statistics have gone up 1000% due to this issue and a few people using iOS10.  Can't imagine the impact the real release will have.

**Comment by EdwinRikkers** [comment]
Can u promise us this issue is fixed before iOS10 is released to the public ? Can u please give us an update.

**Comment by harsaharsa** [comment]
Sorry for the radio silence! Work is ongoing and we're on track to get this fixed before the public release (in September); we'll let you know the moment there's something to test out.

**Comment by EdwinRikkers** [comment]
any updates on this? We are really running out of time, cause we need to upgrade 80+ apps before the public release of iOS 10.
Please give us some idea when we can test the first version...

**Comment by harsaharsa** [comment]
iOS version v5.0.1-rc1 is now available in the Build Service and should work fine on iOS 10. If no issues arise during further testing, we'll promote this to regular v5.0.1 and update the Scanners. Sorry for the wait, and please let us know if you find any new issues below!

One thing we noticed is that since Safari 10 (and thus iOS 10 UIWebView) implements Shadow DOM natively, if you're using Supersonic Web Components (i.e. `<super-navbar>` etc), you need to use the `webcomponents-lite.js` instead of `webcomponents.js` in your layout (it's available in the same Bower package, so just changing that line should work fine).

**Comment by grobitto** [comment]
I have specified custom tab bar active color in ios.css, but in v5.0.1-rc1 tab bar color is blue. 
4.10 works ok

**Comment by harsaharsa** [comment]
Pixate (used the native CSS) was one of the things we had trouble with iOS 10; the project has been abandoned by the original authors for two years now. We're trying to see what's salvageable (navigation bar things for example seem to work fine), but it could be that some of the native styling will unfortunately be unavailable in the iOS 10 -compatible version.

**Comment by grobitto** [comment]
Is there any way to define this color programmatically?

**Comment by harsaharsa** [comment]
You can try calling [`supersonic.ui.tabs.setStyleCSS()`](http://docs.appgyver.com/supersonic/api-reference/stable/supersonic/ui/tabs/setstylecss/) and pass it an inline color string.

**Comment by andybbtt11** [comment]
Working here after changing to webcomponents-lite.  Thanks for coming through on this @harsaharsa .

**Comment by rafaeluzzi** [comment]
only thing not working for me is tab-bar styling ,setting the same rules that worked on 4.0.10 using setStyleCSS() now.. doesn't work either :(

**Comment by EdwinRikkers** [comment]
Thanks. Everything is working fine for us!

**Comment by mtomic** [comment]
Our app hangs on the splash screen with 5.0.1-rc1
OS is iOS 10 Beta 5.

**Comment by harsaharsa** [comment]
@mtomic did you update to use `webcomponents-lite.js`? If you open your app with a debug scanner, are there any JS errors?

**Comment by mtomic** [comment]
@harsaharsa thanks for that. Switching to ```webcomponents-lite.js``` worked.

**Comment by grobitto** [comment]
Is there any chance tab bar coloring will be fixed before final release?

**Comment by rafaeluzzi** [comment]
@grobitto pixate is not working for the tab-bar now.. 
steroids.config.tabBar.tintColor = "#ffffff"
steroids.config.tabBar.tabTitleColor = "#929292"
steroids.config.tabBar.selectedTabTintColor = "#25272A"
# steroids.config.tabBar.backgroundImage = "img/tab@2x.png"
 This works for me for coloring.. But can't get rid of the box shadow as I did with pixate and the 4.0.10 build

**Comment by rafaeluzzi** [comment]
<img width="432" alt="739be800-5d55-11e5-86dc-d42257e3d905" src="https://cloud.githubusercontent.com/assets/43967/18011109/a88e4ffe-6b81-11e6-97ee-597162d92730.png">

This text field size issue is back.. for build 4.0.10 this was working as a workaround for the issue:
collection-view collection-view-cell > view {
  width: 270px;
}

This doesn't work in build 5 anymore.. :(

**Comment by harsaharsa** [comment]
To get the tab bar coloring working fully, we'd need to initialize Pixate straight in `main.m` (which we used to do), but that crashes on iOS 10 due to some conflicting new private APIs. There has been no update to Pixate (in like more than a year), so it looks like the old `steroids.config.tabBar` methods linked by @rafaeluzzi above are the way to go until we circle back on the whole native CSS thing with some better solution. Sorry.

We noticed the prompt window bug resurface too, we'll see what we can do – it's coming from some-years-old Cordova confirm dialog plugin code, so the fix might not be super straight-forward.

**Comment by grobitto** [comment]
@rafaeluzzi @harsaharsa What is the best place to put tab bar config javascript? I googled it, but only get references to application.coffee file, which is absent in supersonic

**Comment by rpb29** [comment]
Hi there

We are having issues opening an in app browser (using window.open) on iOS 10 using build 5.0.1. This was working correctly in 4.0.10.

Unfortunately it is vital to our App 

Is this a known issue? Is there any known workaround?

Many thanks
Russell

**Comment by harsaharsa** [comment]
@rpb29 how are you using InAppBrowser? It's not a very well-coded part of Cordova, and has been giving us gray hairs. Is it possible to open a new layer with the URL instead?

@grobitto old-style tab color config is unfortunately a bit tricky now – the code for setting it up is buried inside https://github.com/AppGyver/steroids/blob/master/src/steroids/Converter.coffee

One option is to downgrade to an old-enough version of Steroids CLI that still generates the application.coffee file and use it in place of app.coffee/structure.coffee

Fixing the prompt width issue requires dropping Pixate altogether, which then disables navbar stylings, which would be a worse situation for most apps. No immediate fix on sight for that, unfortunately.

**Comment by wiwat-tharateeraparb** [comment]
@harsaharsa the prompt width issue is fixed by Pixate. See https://github.com/StylingKit/StylingKit/pull/38. If Steroids can updated Pixate, it could solve this prompt text box width issue (https://github.com/Pixate/pixate-freestyle-ios/issues/178)

**Comment by wiwat-tharateeraparb** [comment]
Is it possible to disable UIAlertController styling instead? Like this one https://github.com/StylingKit/StylingKit/pull/38/commits/efde3d497b1cfa9e6e000f4ac39f924c2f3427d4.

**Comment by mo-zag** [comment]
Hi any updat I have installed debug build scanner 5 but I still get Scanner white screen my app does not load?

Thanks 
Mo

**Comment by lkol** [comment]
@grobitto @harsaharsa It seems you can place the tabBar configuration suggested by @rafaeluzzi  to `app.coffee`. For some reason this works only on a real iOS device, but not with Simulator, but that's good enough for me for now.

```
tabBar:
  enabled: true
  tintColor: "#000000"
  tabTitleColor: "#929292"
  #tabTitleShadowColor: ""
  selectedTabTintColor: "#ff0000"
  backgroundImage: "images/dark-bg.png"
  # selectedTabBackgroundImage:
```

I would like to see the root cause fixed, of course, or at least documentation updated with an appropriate notice.

**Comment by markterrill** [comment]
Hi, rc4 is has broken all of nav/status bar styling. No tint, no icon buttons. Looks pretty average!

After looking at Converter.coffee I also tried adding (with no luck):
 

> navigationBar:
>     enabled: true
>     tintColor: "#E40000"
>     buttonTintColor: "#E40000"
>     titleColor: "#FFFFFF"
>     buttonTitleColor: "#FFFFFF"
>     #tabTitleShadowColor: ""
>     selectedTabTintColor: "#ff0000"

**Comment by markterrill** [comment]
Also trying via supersonic.ui.navigationBar.setStyle didn't work either. Worked in prior versions that run on iOS 10 apparently fine, but not this 6.0.4 train.

Has anyone been able to color the top status/navigation bar? All I want is the background color and text color to be set, a lower priority is getting back the old button icons.

**Comment by justincolangelo** [comment]
@markterrill @grobitto @harsaharsa has this issue been identified? 

>Has anyone been able to color the top status/navigation bar?

**Comment by markterrill** [comment]
@justincolangelo 5.0.1 and tab bar color is there, but the icons are not the color I set them to... It's why I went googling and stumbled over this thread again!
