### ISSUE TITLE
High CPU usage for Scanner on ios emulator with Steroids2 

### ISSUE THREAD

**Issue by vjchem** [AppGyver/steroids#761]
Running the supersonic kitchen sink app and my own app (via the steroids connect on ios emulator, any iphone@8.1) the emulator chews up a lot of CPU on my laptop (e.g., 200-250% in ActivityMonitor). It appears to be consistent for folks running OS X 10.9.

There is a workaround though -- if you start the emulator on its own (e.g., through XCode), then launch scanner in it and open up the last app, the high CPU issue doesn't exist.

Let me know if I can provide any more data.

(for reference: https://forums.appgyver.com/#!/steroids:ios-emulator-cpu-usage)

**Comment by harsaharsa** [comment]
We're running the iOS Simulator via the [ios-sim](https://github.com/phonegap/ios-sim) package – could be that there's something fundamental there that causes high CPU usage. We'll investigate, and thanks for posting a workaround!

**Comment by Arkkimaagi** [comment]
This happens with us on Steroids (non 2 version) too. It's a nice way to get fingers warm on cold winter tho.

**Comment by mikey0000** [comment]
+1

**Comment by kevinsimper** [comment]
I have the same error, hmm.

**Comment by pre** [comment]
Have you experienced any difference with iOS 4.0.3 simulator (Steroids CLI 4.0.8) ? 

iOS Scanner 4.0.3 compiles with 64bit support which could make it more efficient on modern MacBooks.

**Comment by mikey0000** [comment]
You don't seem to understand how ios development is done. There is no simulator provided by steroids. The issue also has nothing to do with the scanner app loaded onto the ios simulator, the ios simulator is provided by xcode. However I have not tried the latest steroids version so will try today. 

The issue is with the way ios-Sim is launching the ios simulator.

**Comment by mikey0000** [comment]
I've tried with latest steroids ios-sim is still going nuts! ios-sim chews the cpu after launch.

**Comment by vjchem** [comment]
Yeah, I'm also seeing the same behavior after upgrading to 4.0.8.

**Comment by lubasch** [comment]
same here

**Comment by terwey** [comment]
:+1: I was already wondering what was causing it, glad I'm not the only one. Also I didn't know that Mac Mini (which has been used well over 2 years) could be THAT loud.

**Comment by jclardy** [comment]
I am having the same issue, CPU goes to 200% (dual core) when launched through steroids connect. Launching via Xcode gives 1-2% max. Workaround works though I haven't tried debugging yet.

**Comment by carlo** [comment]
Same here.

- OS X 10.10.2
- Mac mini (Late 2012)
- 2,6 GHz Intel Core i7
- 16GB RAM

If I can help with by providing any information, please let me know.

**Comment by mirstan** [comment]
+1

**Comment by EdwinRikkers** [comment]
+1

**Comment by 2mia** [comment]
+1

**Comment by mydearxym** [comment]
same here

**Comment by pentateu** [comment]
updating the ios-sim pkg to the latest version fixes the issue... we will release an updated version of steroids CLI with this fix soon.

**Comment by harsaharsa** [comment]
This issue is now fixed with CLI v4.1.5!

**Comment by mirstan** [comment]
Thank you!

**Comment by vindrek** [comment]
Still happens to me on CLI v4.1.22.

OS X 10.11.1 El Capitan
MacBook Pro (Retina, 15-inch, Mid 2015)
2,2 GHz Intel Core i7
16 GB RAM
